# Generated by Django 4.1.5 on 2023-02-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numCon', '0002_researcher_alter_todo_id_user_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='edication',
            new_name='education',
        ),
    ]
